### ISSUE TITLE
Censura False Hitting Words

### ISSUE THREAD

**Issue by AkiraDemi** [YouHaveTrouble/Censura#10]
Censura is hitting words which are
A: Not on the filter
B: Disproportionately punished

The specific cases are ones in which the word "shit" have been hit by the filter and the word "tits" recieved a ban despite being set to a kick.

Here are my current settings:

```yaml
# Should server operators bypass the filters?
op-bypass: true

# Should players be denied to join if their name contains bad words?
kick-on-bad-name: false

# Which events should be checked for bad words?
checks:
  chat: true
  sign: true
  book: true
  command: true
  anvil-name: true
  nametag-use: true

# Should detections that contain filtered words be logged in console
log-detections: true

# Commands of which arguments should be checked.
# It's recommended to list all private message commands and their aliases
# and every command that allows changing item name and etc.
filtered-commands:
  - msg
  - w
  - say
  - me
  - r
  - reply
  - nickname
  - nick

# filter messages based on characters they contain. If message contains characters not
# present in regex, it will be cancelled.
prefilter:
  enabled: false
  regex: "[\\p{L}0-9\\s;.\\/<>()!@#$%^&*|:~+=\\-_,?\"'\\[\\]]+"
  failed: "Censura - Your input contained disallowed characters."

# These characters are replaced by the character on the right before processing.
replacements:
  '0': o
  '1': i
  '3': e
  '4': a
  '5': s
  '7': t
  '9': g
  '$': s
  '@': a

# Check if the current chat message is similiar to the messages sent before
similarity:
  # Should feature be anabled?
  enabled: false
  # How many messages back to check
  message-amount: 3
  # Percentage of how similiar messages should be to be flagged as similar to previous ones
  threshold: 80
  actions:
    - "message: Censura - Stop sending spammy messages, %player%!"

##### FILTERS
# Filters are processed in order from top to bottom
# You can have an unlimited number of filters.
###############################################################
# Each filter has a list of "matches". These are words that are checked for the filter.
# Types of matches:
#   - "fullword" Checks if the sentence contains this word. It must be surrounded by spaces.
#                Besides that, the filter is smart and will ignore any characters in between the word.
#                You can use the * character to bypass the limitation of needing a space: "test*" will match on "testsomething"
#   - "contain"  Checks if the sentence contains the string, the string may be part of another word.
#                Will ignore spaces inside the word unless they're used in an obviously spammy way.
#   - "regex"    Match a simple regex on the string. No smartness involved.
# By default the "fullword" match type is used.

###############################################################
# Each filter can have an unlimited number of "actions". Possible "action" types:
#   - "message: <message>" - sends a message to player who triggered the filter
#   - "command: <command>" - executes command as console.
# Placeholders available for all actions:
# %player% - name of the player who triggered the filter

filter:
  severe:
    action:
      - "command: ban %player% IvorySMP Filter - Using offensive words. Appeal through minecraft tickets if you believe you were falsely caught."
    match:
      - nigger
      - nibber
      - niga
      - niggers
      - niggas
      - whore
      - hitler did nothing wrong
      - heil hitler
      - slut
      - gay is sin
      - gay is a sin
      - tranny
      - faggot
      - trannie
      - fag
      - retard
      - retarded
      - ching chong
      - semen
      - retards
      - mythrodak
      - mythrodack
      - mythro
      - blowjob
      - cum
      - cumming
      - dildo
      - dildos
      - ejaculate
      - ejaculated
      - nigga
      - masterbate
      - masterbating
      - orgasm
      - orgasming
      - orgasms
      - orgy
      - sluts
      - titties
      - titfuck
      - titfucker
  normal:
    action:
      - "command: kick %player% Censura - Please do not use that word. Make a minecraft ticket if you believe the word you used shouldn't have been filtered."
    match:
      - femboy
      - tomboy
      - womb
      - Kanye West
      - kanye west
      - kanye
      - Israel
      - israel
      - Netanhayu
      - netanhayu
      - tit
      - tits
  light:
    action:
      - "command: msg %player% Censura - Stop using bad words, %player%!"
    match:

# Messages used by the plugin
messages:
  no-permission: "Censura - &cYou don't have permission to do this."
  no-such-command: "Censura - &cThere is no such command."
  config-reloaded: "Censura - &aConfiguration reloaded."
  kick-bad-name: "Censura\n&cYour name contains bad words!"
```
